#!/usr/bin/env bash
# ============================================================
# Point the server at one or more hostnames and reload Caddy.
#
#   bash set-domain.sh assetsandcapitalltd.com www.assetsandcapitalltd.com
#
# Run this AFTER the DNS A records already resolve to this VPS. Caddy requests
# a certificate the moment a hostname appears in its config, and Let's Encrypt
# refuses (and rate-limits) hostnames that don't point here yet — so this
# script checks resolution first and refuses rather than burning attempts.
#
# The old hostname is kept alongside the new one on purpose: the site stays
# reachable at srv…hstgr.cloud throughout, which is what you fall back to if
# anything about the new domain misbehaves.
# ============================================================
set -euo pipefail

[[ $# -ge 1 ]] || { echo "usage: set-domain.sh <hostname> [more…]" >&2; exit 1; }

FALLBACK="$(hostname -f 2>/dev/null || true)"
MY_IP="$(curl -fsS --max-time 10 https://api.ipify.org || true)"
[[ -n "$MY_IP" ]] || { echo "✗ could not determine this server's public IP" >&2; exit 1; }
echo "This server is $MY_IP"

for host in "$@"; do
  got="$(dig +short "$host" A | tail -1)"
  if [[ "$got" != "$MY_IP" ]]; then
    echo "✗ $host resolves to '${got:-nothing}', not $MY_IP." >&2
    echo "  Update DNS first and wait for it to propagate, then re-run." >&2
    echo "  Nothing was changed; the site is still live on its current name." >&2
    exit 1
  fi
  echo "✓ $host → $MY_IP"
done

# Keep a restorable copy — one command undoes this if the new domain misbehaves.
cp /etc/caddy/Caddyfile "/etc/caddy/Caddyfile.bak"

HOSTS="$*"
[[ -n "$FALLBACK" && "$HOSTS" != *"$FALLBACK"* ]] && HOSTS="$HOSTS, $FALLBACK"

cat > /etc/caddy/Caddyfile <<EOF
# Generated by deploy/set-domain.sh on $(date -u +%F). The old hostname is kept
# so the site never becomes unreachable during a domain change.

$HOSTS {
	encode zstd gzip
	reverse_proxy 127.0.0.1:3000
	request_body {
		max_size 30MB
	}
}
EOF

caddy validate --config /etc/caddy/Caddyfile >/dev/null 2>&1 || {
  echo "✗ generated config failed validation — restoring previous" >&2
  mv /etc/caddy/Caddyfile.bak /etc/caddy/Caddyfile
  exit 1
}

systemctl reload caddy
echo "✓ Caddy now serving: $HOSTS"
echo "  Certificates are issued on first request; give it ~30s, then load the site."
echo "  Undo: mv /etc/caddy/Caddyfile.bak /etc/caddy/Caddyfile && systemctl reload caddy"
