/**
 * Every translatable string on the site, with where it appears.
 *
 * GENERATED by scripts/extract-strings.mts — do not edit by hand.
 *
 * Extracted by walking the real content objects (lib/content.ts, lib/legal-docs.ts)
 * and the page components, rather than by regexing source. An earlier regex pass
 * pulled in dates, IRR figures, import paths and a slab of raw source; reading the
 * structures is both simpler and exact.
 *
 * Deliberately EXCLUDED, and why:
 *   - business and company names — Atlas Logistics is called that in every language
 *   - sector/stage/instrument/region — a closed vocabulary, translated in dictionaries.ts
 *   - cookie and header identifiers — ac_consent names a real cookie, not a word
 *   - figures, dates, currency codes
 *   - legal text still carrying [CONFIRM] — draft pending counsel, see docs
 *
 * This feeds the admin translation editor, so anything added here becomes
 * translatable in the browser without a deploy.
 */
export type Translatable = { source: string; context: string };

export const TRANSLATABLE: Translatable[] = [
  {
    "source": "A trusted platform for deal-making",
    "context": "About page"
  },
  {
    "source": "Assets and Capital Limited is a financing events company. We serve as an alternative capital-raising and deal-making platform to traditional channels like the stock market and bank financing.",
    "context": "About page"
  },
  {
    "source": "Get in touch",
    "context": "About page"
  },
  {
    "source": "What we stand for",
    "context": "About page"
  },
  {
    "source": "Assets & Capital is a digital investment marketplace connecting vetted businesses seeking capital with a global network of ready investors — for capital raising, partnerships, and market expansion.",
    "context": "Brand"
  },
  {
    "source": "Where quality assets meet ready capital.",
    "context": "Brand"
  },
  {
    "source": "Let's make the connection",
    "context": "Contact page"
  },
  {
    "source": "Whether you're deploying capital or raising it, our team is ready to help. Send us a note and we'll respond within one business day.",
    "context": "Contact page"
  },
  {
    "source": "East Africa Capital Roadshow",
    "context": "Events"
  },
  {
    "source": "Global Investor Forum",
    "context": "Events"
  },
  {
    "source": "Lagos, Nigeria",
    "context": "Events"
  },
  {
    "source": "London, UK",
    "context": "Events"
  },
  {
    "source": "Nairobi, Kenya",
    "context": "Events"
  },
  {
    "source": "West Africa Deal Day",
    "context": "Events"
  },
  {
    "source": "Register interest",
    "context": "Events page"
  },
  {
    "source": "Request a roadshow",
    "context": "Events page"
  },
  {
    "source": "Specialised roadshows and forums that put pre-screened investors and vetted businesses in the same room.",
    "context": "Events page"
  },
  {
    "source": "Where capital meets opportunity",
    "context": "Events page"
  },
  {
    "source": "Everything you need to know about investing and raising capital on Assets & Capital.",
    "context": "FAQ page"
  },
  {
    "source": "Our team is happy to help you get set up, whether you&apos;re deploying capital or raising it.",
    "context": "FAQ page"
  },
  {
    "source": "Still have questions?",
    "context": "FAQ page"
  },
  {
    "source": "Cross-border freight operator with a buy-and-build consolidation thesis.",
    "context": "Featured opportunities"
  },
  {
    "source": "Merchant payments and embedded lending rails processing $400M annually.",
    "context": "Featured opportunities"
  },
  {
    "source": "Precision-farming platform lifting smallholder yields with satellite data.",
    "context": "Featured opportunities"
  },
  {
    "source": "Premium export-focused winemaker with an established distribution footprint.",
    "context": "Featured opportunities"
  },
  {
    "source": "Telehealth and diagnostics network serving 2M+ patients with 140% YoY growth.",
    "context": "Featured opportunities"
  },
  {
    "source": "Utility-scale solar & storage platform expanding across three East African markets.",
    "context": "Featured opportunities"
  },
  {
    "source": "Everything you need to raise with confidence",
    "context": "For businesses page"
  },
  {
    "source": "From listing to closed raise",
    "context": "For businesses page"
  },
  {
    "source": "Register with us",
    "context": "For businesses page"
  },
  {
    "source": "See listing tiers",
    "context": "For businesses page"
  },
  {
    "source": "We don't just list your business — we get it in front of the right investors",
    "context": "For businesses page"
  },
  {
    "source": "We represent one of the largest portfolios of global investors ready to deploy capital. When you work with us, our team acts with urgency and precision to deliver tailored solutions.",
    "context": "For businesses page"
  },
  {
    "source": "Everything you need to deploy with an edge",
    "context": "For investors page"
  },
  {
    "source": "Find opportunities that fit your mandate",
    "context": "For investors page"
  },
  {
    "source": "Our global team engages business owners and screens opportunities to deliver the best options to our investor network — matched to you with advanced technology.",
    "context": "For investors page"
  },
  {
    "source": "Your trusted local partner, worldwide",
    "context": "For investors page"
  },
  {
    "source": "Business score signals",
    "context": "Home — statistics"
  },
  {
    "source": "Listing tiers",
    "context": "Home — statistics"
  },
  {
    "source": "Sectors covered",
    "context": "Home — statistics"
  },
  {
    "source": "Weighted match criteria",
    "context": "Home — statistics"
  },
  {
    "source": "Build a verified profile covering your ask, instrument and financials, then choose a listing tier from Standard to Platinum.",
    "context": "How it works — businesses"
  },
  {
    "source": "Business plan writing, financial modelling and teaser preparation are available separately if your materials need work first.",
    "context": "How it works — businesses"
  },
  {
    "source": "Close the raise",
    "context": "How it works — businesses"
  },
  {
    "source": "Get investor-ready",
    "context": "How it works — businesses"
  },
  {
    "source": "List your opportunity",
    "context": "How it works — businesses"
  },
  {
    "source": "Reach the right investors",
    "context": "How it works — businesses"
  },
  {
    "source": "We route your listing to investors whose mandate matches it, and arrange roadshows where the room justifies one.",
    "context": "How it works — businesses"
  },
  {
    "source": "Work through diligence and negotiation to signed terms. The success fee applies only if the raise closes.",
    "context": "How it works — businesses"
  },
  {
    "source": "Commit, receive your allocation and sign the subscription agreement, with our team in-market throughout.",
    "context": "How it works — investors"
  },
  {
    "source": "Deploy capital",
    "context": "How it works — investors"
  },
  {
    "source": "Diligence & connect",
    "context": "How it works — investors"
  },
  {
    "source": "Get matched",
    "context": "How it works — investors"
  },
  {
    "source": "New opportunities are scored against that mandate as they arrive. You see the ones that fit, along with why each one scored the way it did.",
    "context": "How it works — investors"
  },
  {
    "source": "Open data rooms once the NDA is signed, request a roadshow, and message businesses directly. Every document opened is logged.",
    "context": "How it works — investors"
  },
  {
    "source": "Register your mandate",
    "context": "How it works — investors"
  },
  {
    "source": "Set out your objectives, strategy, geographies, sectors and ticket size. The guided form turns that into a structured mandate in a few minutes.",
    "context": "How it works — investors"
  },
  {
    "source": "Banking, insurance, wealth management, payments",
    "context": "Industries"
  },
  {
    "source": "Clean energy, green infrastructure, water & waste",
    "context": "Industries"
  },
  {
    "source": "EdTech, training services, corporate learning",
    "context": "Industries"
  },
  {
    "source": "Farming, agri-tech, food processing & distribution",
    "context": "Industries"
  },
  {
    "source": "FMCG, retail chains, luxury, food & beverage",
    "context": "Industries"
  },
  {
    "source": "Hotels, resorts, airlines, travel services",
    "context": "Industries"
  },
  {
    "source": "Logistics, machinery, aerospace, automotive, supply chain",
    "context": "Industries"
  },
  {
    "source": "Mining & metals, chemicals, construction materials",
    "context": "Industries"
  },
  {
    "source": "Oil & gas, renewables, energy infrastructure, utilities",
    "context": "Industries"
  },
  {
    "source": "Providers, pharma & biotech, devices, digital health",
    "context": "Industries"
  },
  {
    "source": "Residential, commercial, logistics, hospitality, REITs",
    "context": "Industries"
  },
  {
    "source": "SaaS, cloud, AI/ML, fintech, cybersecurity, e-commerce",
    "context": "Industries"
  },
  {
    "source": "Telecom, broadcasting & streaming, digital media",
    "context": "Industries"
  },
  {
    "source": "Transport, utilities & digital/telecom infrastructure",
    "context": "Industries"
  },
  {
    "source": "Deal Structuring",
    "context": "Insights"
  },
  {
    "source": "For Businesses",
    "context": "Insights"
  },
  {
    "source": "Market Intelligence",
    "context": "Insights"
  },
  {
    "source": "Private credit vs. equity: structuring the right instrument for growth",
    "context": "Insights"
  },
  {
    "source": "The anatomy of a fundable pitch: what investors actually read first",
    "context": "Insights"
  },
  {
    "source": "Why Africa's mid-market is the decade's most mispriced opportunity",
    "context": "Insights"
  },
  {
    "source": "Close",
    "context": "Investment process"
  },
  {
    "source": "Data rooms open once the NDA is signed. Messaging and roadshows run in one place.",
    "context": "Investment process"
  },
  {
    "source": "Each opportunity is scored against your written mandate before it reaches you.",
    "context": "Investment process"
  },
  {
    "source": "Engage",
    "context": "Investment process"
  },
  {
    "source": "Financials, ownership and documents are verified before a listing goes live.",
    "context": "Investment process"
  },
  {
    "source": "Match",
    "context": "Investment process"
  },
  {
    "source": "Screen",
    "context": "Investment process"
  },
  {
    "source": "Term sheets, agreements and allocation are tracked through to funding.",
    "context": "Investment process"
  },
  {
    "source": "30 days",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "6 months",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "7 days",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "ac-theme",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Analytics",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Category",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Cookie Policy",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Cookies are small files stored by your browser. We use as few as possible, and none that are not strictly necessary without your permission.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Cookies we use",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "If you allow analytics, we measure which parts of the platform are used so we can improve them. This is aggregate — we do not use it to identify you or to advertise to you.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Keeps you signed in. Signed, HTTP-only.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Managing cookies in your browser",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Marketing",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Name",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Pre-launch access. Only set if you enter a preview code.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Purpose",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Remembers light/dark preference. Stored in your browser, not sent to us.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Remembers your cookie choices so we do not ask on every page.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Retention",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Strictly necessary",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "This table is generated from the application itself, so it reflects what is actually set:",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Until cleared",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "We do not currently use advertising or retargeting cookies. The choice exists in our preference centre so that nothing of the kind can be introduced without your consent.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "When you first visit we ask what you allow. Nothing beyond strictly necessary cookies is set until you choose, rejecting is exactly as easy as accepting, and you can change your mind at any time from Settings → Your data and privacy, or the cookie link in the footer.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "You can also block or delete cookies in your browser settings. Blocking strictly necessary cookies will stop you signing in, because that is what they do.",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Your choices",
    "context": "Legal — Cookie Policy"
  },
  {
    "source": "Assets & Capital provides a marketplace and related services. Nothing on the platform constitutes investment, legal, or tax advice, or an offer or solicitation to buy or sell any security.",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Disclosures",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Not investment advice",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Private-market investments carry risk, including the risk of losing capital, and are typically illiquid. Past performance is not indicative of future results.",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Risk",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Vetting",
    "context": "Legal — Disclosures"
  },
  {
    "source": "While we screen and verify businesses before listing, investors are responsible for their own due diligence. Match scores are informational signals, not recommendations.",
    "context": "Legal — Disclosures"
  },
  {
    "source": "Access a copy of your data — download it as a file at any time.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Account data — for as long as your account is open, then deleted or anonymised when you close it.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Changes",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Children",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Complain to a supervisory authority. In Ghana this is the Data Protection Commission; in the UK the ICO; in the EU your national authority. We would rather you came to us first.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Cookie consent records — 6 months, after which we ask again.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Correct anything inaccurate — edit it in your profile, or ask us.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Data collected automatically — sign-in activity, security logs, and, if you consent, aggregate usage measurement. We do not build advertising profiles.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Data you give us — name, email, password, organisation details, investment mandate or business listing information, documents you upload, and messages you send through the platform.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Delete your account — we remove your personal details. Records we must keep by law are retained in anonymised form; we tell you this rather than claiming a deletion we cannot perform.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "How long we keep it",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Identity and compliance data — where you invest or raise capital through us, verification data such as legal name, country, and the outcome of identity, sanctions and politically-exposed-person checks.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "If we change how we use personal data we will update this page and, where the change is significant, tell you directly. The date at the top shows when it was last revised.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Object to or restrict processing based on legitimate interests.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Passwords are stored hashed with bcrypt and are never recoverable, sessions are signed and HTTP-only, and traffic is encrypted in transit with HTTPS. Access to production data is limited to staff who need it. Backups are taken daily and stored off-site. No system is perfectly secure, and we will notify you and the relevant authority without undue delay if a breach affects your data.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Portability — your export is machine-readable JSON.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Privacy Policy",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Security",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "The platform is for businesses and professional or accredited investors. It is not directed at anyone under 18, and we do not knowingly collect their data.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "This notice explains what personal data Assets and Capital Limited collects, why, what we do with it, and the rights you have over it.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "To keep the service secure — rate limiting, audit logs, fraud prevention. Basis: legitimate interests.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "To measure how the platform is used. Basis: your consent, which you can withdraw at any time.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "To provide the platform — matching investors with opportunities, hosting listings, enabling messaging. Basis: performance of a contract.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "To send service messages you have asked for. Basis: consent, or contract where the message is necessary to the service.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "To verify identity and prevent financial crime — KYC, sanctions and AML screening. Basis: legal obligation, and our legitimate interest in a trustworthy marketplace.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "We collect only what the service needs, in three groups:",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "We keep personal data only as long as we need it:",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "We must have a lawful basis for each use. Ours are:",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "What we collect",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Where your data is held",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Who is responsible for your data",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Who we share it with",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Why we use it, and our legal basis",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Withdraw consent — change your cookie choices at any time, as easily as you gave them.",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "You can exercise most of these yourself from Settings → Your data and privacy, without contacting us. You have the right to:",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Your rights",
    "context": "Legal — Privacy Policy"
  },
  {
    "source": "Agreement",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "By using Assets & Capital, you agree to these terms. If you do not agree, please do not use the platform.",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "Fees",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "Governing law",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "Limitation of liability",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "Terms of Service",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "The platform",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "The platform is provided on an 'as is' basis. To the fullest extent permitted by law, we are not liable for investment outcomes or decisions made using the platform.",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "We provide a marketplace connecting investors with businesses seeking capital, and related services. We are a facilitator and do not provide investment, legal, or tax advice.",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "You are responsible for keeping your credentials secure and for activity under your account. Tell us promptly if you believe it has been compromised.",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "Your account",
    "context": "Legal — Terms of Service"
  },
  {
    "source": "About us",
    "context": "Navigation"
  },
  {
    "source": "Aligned incentives",
    "context": "Navigation"
  },
  {
    "source": "Browse the marketplace",
    "context": "Navigation"
  },
  {
    "source": "Build your mandate",
    "context": "Navigation"
  },
  {
    "source": "Business Services",
    "context": "Navigation"
  },
  {
    "source": "Company",
    "context": "Navigation"
  },
  {
    "source": "Contact",
    "context": "Navigation"
  },
  {
    "source": "Deals scored against your mandate",
    "context": "Navigation"
  },
  {
    "source": "Defensible projections",
    "context": "Navigation"
  },
  {
    "source": "Events",
    "context": "Navigation"
  },
  {
    "source": "For Investors",
    "context": "Navigation"
  },
  {
    "source": "Get matched automatically",
    "context": "Navigation"
  },
  {
    "source": "How it works",
    "context": "Navigation"
  },
  {
    "source": "Insights",
    "context": "Navigation"
  },
  {
    "source": "Invest",
    "context": "Navigation"
  },
  {
    "source": "Investor Services",
    "context": "Navigation"
  },
  {
    "source": "Investor-ready narrative",
    "context": "Navigation"
  },
  {
    "source": "List your business",
    "context": "Navigation"
  },
  {
    "source": "Make a strong first impression",
    "context": "Navigation"
  },
  {
    "source": "Market intelligence & research",
    "context": "Navigation"
  },
  {
    "source": "Marketplace",
    "context": "Navigation"
  },
  {
    "source": "Meet pre-screened opportunities",
    "context": "Navigation"
  },
  {
    "source": "On-the-ground market insight",
    "context": "Navigation"
  },
  {
    "source": "Our mission and team",
    "context": "Navigation"
  },
  {
    "source": "Pricing",
    "context": "Navigation"
  },
  {
    "source": "Raise Capital",
    "context": "Navigation"
  },
  {
    "source": "Roadshows and forums",
    "context": "Navigation"
  },
  {
    "source": "Screened and verified listings",
    "context": "Navigation"
  },
  {
    "source": "Standard & premium tiers",
    "context": "Navigation"
  },
  {
    "source": "Success-fee model",
    "context": "Navigation"
  },
  {
    "source": "Suppliers, buyers, partners",
    "context": "Navigation"
  },
  {
    "source": "Talk to our team",
    "context": "Navigation"
  },
  {
    "source": "Teaser & pitch prep",
    "context": "Navigation"
  },
  {
    "source": "Why invest with us",
    "context": "Navigation"
  },
  {
    "source": "90-day listing window",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "A managed raise, run by our team end to end.",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Actively promoted to matched investors.",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Appears in marketplace search",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Basic performance analytics",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Be visible to investors searching the marketplace.",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Business plan & financial modelling",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Data room (up to 25 documents)",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Dedicated deal manager",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Direct mandate-matched outreach",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Everything in Gold",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Everything in Silver",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Everything in Standard",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Extended 180-day window",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Featured-opportunity badge",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Higher placement, plus a data room for your documents.",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Homepage & newsletter features",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Multiple targeted roadshows",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "One personalised roadshow",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Priority search placement",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Priority success-fee terms",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Secure messaging with investors",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Shadow investor search",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Verified business listing",
    "context": "Pricing — listing tiers"
  },
  {
    "source": "Add expert support as you need it",
    "context": "Pricing page"
  },
  {
    "source": "Free to join. Subscribe to go deep.",
    "context": "Pricing page"
  },
  {
    "source": "List your business to reach our global investor network, add expert services as you need them, and pay a success fee only when a deal closes.",
    "context": "Pricing page"
  },
  {
    "source": "Pay a success fee only when you close",
    "context": "Pricing page"
  },
  {
    "source": "Questions, answered",
    "context": "Pricing page"
  },
  {
    "source": "Registering and browsing core details is always free. An investor subscription unlocks full business details across the marketplace — then expressing interest opens each business's data room, AI profile and your personalised match rate.",
    "context": "Pricing page"
  },
  {
    "source": "Simple tiers. Aligned incentives.",
    "context": "Pricing page"
  },
  {
    "source": "Build your investment mandate",
    "context": "Registration"
  },
  {
    "source": "Choose your path — it takes just a few minutes to get set up.",
    "context": "Registration"
  },
  {
    "source": "Create a verified profile with your ask and the services you need. We actively put your opportunity in front of the investors whose mandate fits.",
    "context": "Registration"
  },
  {
    "source": "List your business, reach ready capital",
    "context": "Registration"
  },
  {
    "source": "Tell us your objectives, strategy, geographies and ticket size. We'll match you with opportunities that fit — and only notify you when they do.",
    "context": "Registration"
  },
  {
    "source": "Which side of the deal are you on?",
    "context": "Registration"
  },
  {
    "source": "A teaser and deck written to earn the second meeting.",
    "context": "Services"
  },
  {
    "source": "Business plan writing",
    "context": "Services"
  },
  {
    "source": "Events in the markets you are targeting, hosted alongside operators and advisers who work there.",
    "context": "Services"
  },
  {
    "source": "Financial modelling",
    "context": "Services"
  },
  {
    "source": "Introductions to suppliers, buyers and partners once the investment is made.",
    "context": "Services"
  },
  {
    "source": "Local events access",
    "context": "Services"
  },
  {
    "source": "Market access support",
    "context": "Services"
  },
  {
    "source": "Models where every assumption is stated and can be traced back to its source.",
    "context": "Services"
  },
  {
    "source": "Plans built around what investors read first: the market, the model, the numbers and the team.",
    "context": "Services"
  },
  {
    "source": "Sessions built around your mandate, with every business screened against it before the invitation goes out.",
    "context": "Services"
  },
  {
    "source": "Specialised roadshows",
    "context": "Services"
  },
  {
    "source": "Teaser & pitch preparation",
    "context": "Services"
  },
  {
    "source": "Businesses pay a success fee when a raise closes. If it doesn't close, there's no fee to collect.",
    "context": "Why us"
  },
  {
    "source": "Every opportunity is scored on fifteen weighted criteria drawn from your written mandate, and each score shows the reasoning behind it.",
    "context": "Why us"
  },
  {
    "source": "Financials, ownership and documents are checked before a business goes live. Listings that fail that check never reach the marketplace.",
    "context": "Why us"
  },
  {
    "source": "Our team meets business owners where they operate, so what reaches you is informed by more than a data room.",
    "context": "Why us"
  },
  {
    "source": "Paid on outcomes",
    "context": "Why us"
  },
  {
    "source": "People in the market",
    "context": "Why us"
  },
  {
    "source": "Scored against your mandate",
    "context": "Why us"
  },
  {
    "source": "Screened before listed",
    "context": "Why us"
  }
];
